**NumPy Array Indexing**

In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr[0, 1])
print(arr[0][1])

2nd element on 1st row:  2
2


In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [5]:
# Negative Indexing

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10



**NumPy Array Slicing**

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
