np.arange() is a fundamental function in the NumPy library for numerical computing. It allows you to create an array with evenly spaced values within a specified range. Think of it as an enhanced version of Python’s built-in range() function, but with more flexibility and capabilities.

Basic Usage:

The most common form of numpy.arange() takes three arguments: start, stop, and step.

It returns an array with values ranging from start (inclusive) up to, but excluding the stop value, with a specified step between them.

The resulting array is an ndarray (NumPy array).

Syntax:

numpy.arange([start,] stop [, step,] [, dtype=None])

Parameters:


start: (optional) Start of the interval. The default start value is 0.

stop: End of the interval. The interval does not include this value.

step: (optional) Spacing between values. Default step size is 1.

dtype: (optional) The data type of the output array. If not specified, it’s inferred from other input arguments.

In [6]:
# Generate integers from 0 to 9:

import numpy as np
arr1 = np.arange(10)

print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# Specify a start value:

arr2 = np.arange(5, 15)

print(arr2)

[ 5  6  7  8  9 10 11 12 13 14]


In [13]:
# Set a custom step:

arr3 = np.arange(0, 20, 2)

print(arr3)

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
# Use a non-integer step:

arr4 = np.arange(0, 1, 0.1)

print(arr4)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [15]:
# Specify a data type:

arr5 = np.arange(0, 5, dtype=float)

print(arr5)

[0. 1. 2. 3. 4.]


Warnings:

Be cautious when using non-integer steps. For precise spacing, consider using numpy.linspace.

Precision loss can occur due to casting or floating point overflow, especially for large values.